env:
  node: true
  es6: true
  mocha: true

# need babel-eslint because default eslint doesn't support optional chaining
parser: "@babel/eslint-parser"
parserOptions: {
  requireConfigFile: false
}

rules:
  strict: 0
  no-var: 1
  no-unused-vars: 1
  no-console: 0
  no-mixed-spaces-and-tabs: 2
  no-useless-escape: 0
  indent: ["warn", "tab", { "SwitchCase": 1}]

extends: eslint:recommended
