env:
  node: true
  es6: true
  mocha: true

rules:
  strict: 0
  no-var: 1
  no-unused-vars: 1
  no-mixed-spaces-and-tabs: 1
  no-console: 0
  indent: ["warn", "tab", { "SwitchCase": 1}]

extends: eslint:recommended

plugins: [ejs]
