apiVersion: v1
kind: Service
metadata:
  name: "{{tag '  .Chart.Name '}}-service"
  labels:
    chart: "{{tag ' .Chart.Name '}}-{{tag ' .Chart.Version | replace "+" "_" '}}"
spec:
  type: {{tag ' .Values.service.type '}}
  ports:
{{#if deploy_options.servicePorts.https}}
  - name: https
    port: {{tag ' .Values.service.servicePortHttps '}}
{{/if}}
  - name: http
    port: {{tag ' .Values.service.servicePort '}}
  selector:
    app: "{{tag '  .Chart.Name '}}"

